[package]
org = "ballerina"
name = "bal_backend"
version = "0.1.0"
distribution = "2201.10.2"

[build-options]
observabilityIncluded = true

[[platform.java21.dependency]]
groupId = "org.postgresql"
artifactId = "postgresql"
version = "42.7.2"
path = "./lib/postgresql-42.7.2.jar"
